package com.trex.agenticaccessibility.accessibility

import android.accessibilityservice.AccessibilityService
import android.accessibilityservice.GestureDescription
import android.graphics.Path
import android.view.accessibility.AccessibilityNodeInfo
import com.trex.agenticaccessibility.agent.ActionResult
import com.trex.agenticaccessibility.ai.*

object AccessibilityBridge {
    @Volatile private var service: AccessibilityService? = null
    fun attach(s: AccessibilityService) { service = s }
    fun detach() { service = null }
    fun onEvent(event: android.view.accessibility.AccessibilityEvent?) { }
    fun observe(): UiSnapshot? { val s=service ?: return null; val root=s.rootInActiveWindow ?: return null; return try { UiObserver.snapshot(root, root.packageName?.toString() ?: "unknown") } finally { root.recycle() } }
    fun execute(a: AgentAction): ActionResult { val s=service ?: return ActionResult(false,"Accessibility service unavailable"); return try { when(a.type) { ActionType.TAP->tap(s,a.target); ActionType.TYPE->type(s,a.text?:""); ActionType.CLEAR_TEXT->type(s,""); ActionType.SCROLL->scroll(s,a.direction?:"down"); ActionType.SWIPE->swipe(s,a.x?:500f,a.y?:900f,a.durationMs); ActionType.BACK->ActionResult(s.performGlobalAction(AccessibilityService.GLOBAL_ACTION_BACK),"Back"); ActionType.HOME->ActionResult(s.performGlobalAction(AccessibilityService.GLOBAL_ACTION_HOME),"Home"); ActionType.OPEN_APP->openApp(s,a.packageName?:a.target?:""); ActionType.WAIT,ActionType.OBSERVE->ActionResult(true,"Observed"); ActionType.SCREENSHOT->ActionResult(false,"Screenshot capture is intentionally not persisted in MVP"); ActionType.REQUEST_USER_CONFIRMATION->ActionResult(false,"Confirmation required"); ActionType.FINISH_TASK->ActionResult(true,"Complete") } } catch(e:Exception) { ActionResult(false,e.message?:"Action failed") } }
    private fun tap(s:AccessibilityService,target:String?):ActionResult { if(target.isNullOrBlank())return ActionResult(false,"Missing tap target"); val r=s.rootInActiveWindow?:return ActionResult(false,"No active window"); val n=find(r,target);r.recycle();if(n==null)return ActionResult(false,"UI target not found: $target");val ok=if(n.isClickable)n.performAction(AccessibilityNodeInfo.ACTION_CLICK) else n.parent?.performAction(AccessibilityNodeInfo.ACTION_CLICK)?:false;n.recycle();return ActionResult(ok,"Tapped $target") }
    private fun find(n:AccessibilityNodeInfo,target:String):AccessibilityNodeInfo? { if(listOf(n.text?.toString(),n.contentDescription?.toString(),n.viewIdResourceName).any{it?.equals(target,true)==true})return AccessibilityNodeInfo.obtain(n);for(i in 0 until n.childCount){n.getChild(i)?.let{c->val f=find(c,target);c.recycle();if(f!=null)return f}};return null }
    private fun type(s:AccessibilityService,text:String):ActionResult { val r=s.rootInActiveWindow?:return ActionResult(false,"No active window");val f=r.findFocus(AccessibilityNodeInfo.FOCUS_INPUT)?:r.findFocus(AccessibilityNodeInfo.FOCUS_ACCESSIBILITY);r.recycle();if(f==null)return ActionResult(false,"No editable field focused");val b=android.os.Bundle().apply{putCharSequence(AccessibilityNodeInfo.ACTION_ARGUMENT_SET_TEXT_CHARSEQUENCE,text)};val ok=f.performAction(AccessibilityNodeInfo.ACTION_SET_TEXT,b);f.recycle();return ActionResult(ok,"Text field updated") }
    private fun scroll(s:AccessibilityService,direction:String):ActionResult { val r=s.rootInActiveWindow?:return ActionResult(false,"No active window");val n=findScrollable(r);r.recycle();if(n==null)return ActionResult(false,"No scrollable UI");val ok=n.performAction(if(direction.equals("up",true))AccessibilityNodeInfo.ACTION_SCROLL_BACKWARD else AccessibilityNodeInfo.ACTION_SCROLL_FORWARD);n.recycle();return ActionResult(ok,"Scrolled $direction") }
    private fun findScrollable(n:AccessibilityNodeInfo):AccessibilityNodeInfo? { if(n.isScrollable)return AccessibilityNodeInfo.obtain(n);for(i in 0 until n.childCount){n.getChild(i)?.let{c->val f=findScrollable(c);c.recycle();if(f!=null)return f}};return null }
    private fun swipe(s:AccessibilityService,x:Float,y:Float,d:Long):ActionResult {val p=Path().apply{moveTo(x,y);lineTo(x,y-400)};val g=GestureDescription.Builder().addStroke(GestureDescription.StrokeDescription(p,0,d.coerceIn(100,2000))).build();return ActionResult(s.dispatchGesture(g,null,null),"Swipe dispatched")}
    private fun openApp(s:AccessibilityService,nameOrPackage:String):ActionResult {if(nameOrPackage.isBlank())return ActionResult(false,"Missing app name");val pm=s.packageManager;var pkg=nameOrPackage;if(pm.getLaunchIntentForPackage(pkg)==null){pkg=pm.getInstalledApplications(0).firstOrNull{pm.getApplicationLabel(it).toString().equals(nameOrPackage,true)}?.packageName?:return ActionResult(false,"App not installed: $nameOrPackage")};val i=pm.getLaunchIntentForPackage(pkg)?:return ActionResult(false,"No launcher activity: $pkg");i.addFlags(android.content.Intent.FLAG_ACTIVITY_NEW_TASK);s.startActivity(i);return ActionResult(true,"Opening $nameOrPackage")}
}
